export enum CaseStatus {
  UNASSIGNED = 'UNASSIGNED',
  PENDING = 'PENDING',
  REVIEW = 'REVIEW',
  SENT = 'SENT',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
  CANCELLED = 'CANCELLED',
}

export enum ApplicantFamilyMembers {
  ALONE = 'ALONE',
  SPOUSE = 'SPOUSE',
  CHILD = 'CHILD',
  PARTNER = 'PARTNER',
  SPOUSE_AND_CHILD = 'SPOUSE_AND_CHILD',
  PARTNER_AND_CHILD = 'PARTNER_AND_CHILD',
}
