export const USER_REPOSITORY_TOKEN = 'USER_REPOSITORY_TOKEN';
export const QUESTION_REPOSITORY_TOKEN = 'QUESTION_REPOSITORY_TOKEN';
export const TEST_REPOSITORY_TOKEN = 'TEST_REPOSITORY_TOKEN';
export const QUESTION_GROUP_REPOSITORY_TOKEN =
  'QUESTION_GROUP_REPOSITORY_TOKEN';
