export const USER_REPOSITORY_TOKEN = 'USER_REPOSITORY_TOKEN';
export const QUESTION_REPOSITORY_TOKEN = 'QUESTION_REPOSITORY_TOKEN';
export const TEST_REPOSITORY_TOKEN = 'TEST_REPOSITORY_TOKEN';
export const QUESTION_GROUP_REPOSITORY_TOKEN =
  'QUESTION_GROUP_REPOSITORY_TOKEN';
export const TIME_OFF_TOKEN = 'TIME_OFF_TOKEN';
export const TIME_OFF_TOKEN_REQUEST = 'TIME_OFF_TOKEN_REQUEST';
export const CASE_REPOSITORY_TOKEN = 'CASE_REPOSITORY_TOKEN';
export const PROVIDER_REPOSITORY_TOKEN = 'PROVIDER_REPOSITORY_TOKEN';
export const CASE_REQUEST_REPOSITORY_TOKEN = 'CASE_REQUEST_REPOSITORY_TOKEN';
export const AUTH_SERVICE_TOKEN = 'AUTH_SERVICE_TOKEN';
export const FILE_SERVICE_TOKEN = 'FILE_SERVICE_TOKEN';
export const DOCUMENTS_REPOSITORY_TOKEN = 'DOCUMENTS_REPOSITORY_TOKEN';
