export const USER_REPOSITORY_TOKEN = 'USER_REPOSITORY_TOKEN';
export const QUESTION_REPOSITORY_TOKEN = 'QUESTION_REPOSITORY_TOKEN';
export const TEST_REPOSITORY_TOKEN = 'TEST_REPOSITORY_TOKEN';
export const QUESTION_GROUP_REPOSITORY_TOKEN =
  'QUESTION_GROUP_REPOSITORY_TOKEN';
export const TIME_OFF_TOKEN = 'TIME_OFF_TOKEN';
export const TIME_OFF_TOKEN_REQUEST = 'TIME_OFF_TOKEN_REQUEST';
export const CASE_REPOSITORY_TOKEN = 'CASE_REPOSITORY_TOKEN';
