export enum EmploymentStatus {
  PENDING = 'PENDING',
  ACTIVE = 'ACTIVE',
  INACTIVE = 'INACTIVE',
  TERMINATED = 'TERMINATED',
}

export enum UserRoles {
  ADMIN = 'ADMIN',
  SUPER_ADMIN = 'SUPER_ADMIN',
  PROVIDER_EMPLOYEE = 'PROVIDER_EMPLOYEE',
  PROVIDER_SUPERVISOR = 'PROVIDER_SUPERVISOR',
  EMPLOYER_SUPERVISOR = 'EMPLOYER_SUPERVISOR',
  EMPLOYER_EMPLOYEE = 'EMPLOYER_EMPLOYEE',
  CUSTOMER = 'CUSTOMER',
}
